server:
  servlet:
    context-path: /api
  port: 8080
  ssl:
    enabled: true
    key-store: src/main/resources/AN-keystore.p12
    key-store-password: Kimchoilee1!
    key-store-type: PKCS12
    key-alias: AN-keystore

spring:
  application:
    name: echocircle
  datasource:
    url: jdbc:mysql://localhost:3306/echocircle?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Kimchoilee1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/echocircle
  output:
      ansi:
        enabled: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


