server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: echocircle
  datasource:
    url: jdbc:mysql://localhost:3306/echocircle?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Kimchoilee1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true